### ISSUE TITLE
Is there a way to not specify the limit in search_all?

### ISSUE THREAD

**Issue by pwichmann** [tristantao/py-bing-search#11]
First, thank you for your work!

Is there a way to not specify the limit in search_all and just receive all results that Bing can provide?

**Comment by tristantao** [comment]
Believe it or not, your request made me spend an hour to rewrite the whole thing.

It now has a different behavior and you'll be able to continuously call search to grab the next page (as long as you have enough credits). This is as "unlimited" as it gets. I'm assuming you didn't mean receive back the entire 1.3 billion search results?

The issue is that I believe they limit the API call to only return 50 results per call, so you'd have to call it multiple times.

Check out the updated (or updating) README for more info.

**Comment by pwichmann** [comment]
Thank you for doing this!
I appreciate your effort and did not want to leave this uncommented.
Thank you!

**Comment by tristantao** [comment]
You're very welcome :) I was just glad someone cared enough about the package to want different features!
